name: Automerge

on:
  schedule:
    - cron: 0 * * * *
  pull_request_target:
    types:
      - opened
      - synchronized
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          merge-method: rebase
          pull-request: ${{ github.event.inputs.pull-request }}
          dry-run: true
