name: UMINO Project
on:
  issues:
    types:
      - opened
      - reopened
      - assigned
      - unassigned
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
      - assigned
      - unassigned

env:
  inbox: Inbox
  in_progress: In Progress
  gh_project_token: ${{ secrets.GH_TOKEN }}
  user: HiromiShikata
  project_id: 48

jobs:
  move_to_inbox:
    name: opened_or_reopened
    runs-on: ubuntu-latest
    if: >-
      (github.event_name == 'issues' && github.event.issue.state == 'open') || 
      (github.event_name == 'pull_request' && github.event.pull_request.state == 'open') &&
      (github.event.action == 'opened' || github.event.action == 'reopened' || 
      github.event.action == 'assigned' || github.event.action == 'unassigned')
    steps:
      - name: Move issue to ${{ env.inbox }}
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ env.gh_project_token }}
          user: ${{ env.user }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
          status_value: ${{ env.inbox }}
